### ISSUE TITLE
Improve vertical alignment

### ISSUE THREAD

**Issue by juancampa** [dmackdev/egui_json_tree#6]
<img width="303" alt="Screenshot 2023-09-06 at 11 36 17 PM" src="https://github.com/dmackdev/egui_json_tree/assets/1410520/f38cf9d4-45e8-4830-ade3-36d8131ee8de">

Keys and open/close delimiters should probably be horizontally aligned.

**Comment by dmackdev** [comment]
I think this must be something specific to how you've styled the `egui::Ui` in which you are rendering the `JsonTree`, because I do not see this problem in this repo's examples, and I notice that the vertical line is missing from your screenshot.

Are you able to provide a reproduction? I suspect it's because `ui.spacing().icon_width` has changed - changing this in the demo causes a similar misalignment.

**Comment by juancampa** [comment]
Interesting, I didn't change `icon_width` but I did change the font size. Perhaps I need to adjust `icon_width` accordingly

**Comment by juancampa** [comment]
To be clear, you don't see either of the misalignments?

**Comment by juancampa** [comment]
<img width="239" alt="Screenshot 2023-09-07 at 2 11 46 AM" src="https://github.com/dmackdev/egui_json_tree/assets/1410520/6244f799-4ce3-4dc2-87b5-42d0f3220824">
You're right, changing it to `8.0` fixed the key alignment issue

**Comment by dmackdev** [comment]
I am not seeing a misalignment in the repo's `examples` when changing the font size and style alone, e.g. setting the following on a `JsonTree`:
```
 .style(JsonTreeStyle {
                font_id: Some(FontId::proportional(40.0)),
                ..Default::default()
            })
```
Did you change something else?
Wondering if we should set an appropriately scaled `icon_width` based on something in the `Ui`.
